

kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "smashing-pipeline"
spec:
    source:
      git:
        ref: develop
        uri: https://github.com/GeraudWilling/smashing-poc.git
      type: Git
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: jenkinsfile
      type: JenkinsPipeline
