
kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "smashing-pipeline"
spec:
    source:
      git:
        ref: ${SOURCE_REPOSITORY_REF}
        uri: ${SOURCE_REPOSITORY_URL}
      type: Git
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: jenkinsfile
      type: JenkinsPipeline
